#!/bin/sh

srcdir=`dirname $0`
srcdir=`cd $srcdir; pwd`

progname=$0
progname="$progname.x"


# ==================================
# Process the command line arguments
# ==================================

all_arg=$*
args=

while :
do
# no args
        case $# in
	0)
		break
		;;
	esac

# get first arg and shuffle
	option=$1
	shift

# make all options have two hyphens
	orig_option=$option
	case $option in
		--*) ;;
		-*) option=-$option ;;
	esac

# split the option to get its argument
	case $option in
	--*=*)
		optarg=`echo $option | sed -e 's/^[^=]*=//'`
		;;
	esac

# process the options
	case $option in

	    --xml_system_configuration=*) inx=$optarg;;
	    --xml_system_metrics=*)	  oux=$optarg;;
	esac
done

/usr/bin/env python $srcdir/xml_stub.py --program=$progname --xml_system_configuration=$inx --xml_system_metrics=$oux


