

run-%:
	/opt/bin/most -x design_space.xml -f most/$*.scr -p

clean:
	rm -f check normal_* rand_* st_shell_*.scr *.pdf *.png D-* tmp-*

# peffect:
# 	/home/zaccaria/projects/stshell_mexp/build/image/bin/most -x design_space.xml -f most/plot_effect.scr -p
# 	pstopdf effect.ps
# 	putfile effect.pdf

# pfr:
# 	/home/zaccaria/projects/stshell_mexp/build/image/bin/most -x design_space.xml -f most/pfr.scr -p
# 	putfile report-dist.pdf

# pef:
# 	/home/zaccaria/projects/stshell_mexp/build/image/bin/most -x design_space.xml -f most/pef.scr -p
# 	putfile report-effect.pdf

# rules:
# 	/home/zaccaria/projects/stshell_mexp/build/image/bin/most -x design_space.xml -f most/rules.scr -p

# mcat:
# 	/home/zaccaria/projects/stshell_mexp/build/image/bin/most -x design_space.xml -f most/cat_out_table.scr -p
# 	gnuplot scripts/roofline.scr
# 	pstopdf balance.ps
# 	putfile balance.pdf

