name: MOST build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://vzaccaria/most:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build MOST
      run: |
          mkdir build
          cd build
          ../bootstrap.sh
          make
    - name: Test MOST
      run: |
          make test
